### ISSUE TITLE
problem with installation when path contains a space

### ISSUE THREAD

**Issue by pdl86** [gotthardp/lorawan-server#158]
While trying Lorawan-server on 
windows 10 / Erlan 19 or 20 

a) the  location of the "lorawan-server.bat" file is incorrectly described in the documentation as "bin" while it is  "scripts" 
b) when launching the bat file, it failed  stating 

"could not start kernel pid (application_controller) (error in config file "releases/{{release_version}}/sys.config" (none): configuration file not found)

Crash dump is being written to: erl_crash.dump...done
"

there is no "sys.config" file in erl realeases/release_version directory (  both 19 and 20 ) 

( unless the erl install is different on Linux, as the command is almost the same in the bash script, it may fail also on linux)

c) there is an issue with the command  "set FILES=!FILES! %%A\ebin", when %%A contains a space 
( strange as when used in the third command of the script , it works )

Any help will be appreciated 
best regards
philippe

**Comment by gotthardp** [comment]
Hello. The "lorawan-server.bat" is actually in the "bin" directory. You probably downloaded a source package (where the .bat is in scripts), which cannot be executed. Please use the binary release.

**Comment by gotthardp** [comment]
the "set FILES=!FILES! %%A\ebin" related issue is a bug, which I will fix

**Comment by gotthardp** [comment]
I just fixed the space-related issue. Thanks for reporting this.

**Comment by pdl86** [comment]
Hi Petr

I have nstalled  the 0.4.7, this time as a binary,  ( oops ) , but the "banl" issue is still there 
if install in a directory as "D:\No Backup\temp-install\lorawan-srv-gotthardp\lorawan-server\bin"
the results in the FILES variavle is still"No"
if installed in "D:\test\lorawan-sver\bin" the FILES variables is correctly set 

so there is a trick somwhere, and I'm not sufivently skille din the cmd subtle things to find it .

**Comment by pdl86** [comment]
@gotthardp

**Comment by pdl86** [comment]
@gotthardp 
please have a look, the "bug" on blank intoa directory name is still there

**Comment by gotthardp** [comment]
@pdl86 I just made another fix. You can have a look at the above mentioned patch and move the `"` quotation marks are indicated, or wait for the next release (in 1-2 weeks). Thanks for reporting this.

**Comment by gotthardp** [comment]
V0.4.8 released

**Comment by pdl86** [comment]
Hi

thanks

confirm it works.

regards

philippe


Le 31/07/2017 à 15:03, Petr Gotthard a écrit :

**Comment by olegscorpion** [comment]
Hello Gotthardp my name is Oleg. i'm from Kazakhstan.
i need help.
I am trying your server. Installed Earl 25, after starting the bin server.bat gives an error:
C:\lorawan-server-0.6.7\bin\lorawan-server.bat
Server started at http://localhost:8080
{"init terminating in do_boot",{undef,[{lorawan_app,start,[],[]},{init,start_em,1,[{file,"init.erl"},{line,1220}]},{init,do_boot,3,[{file,"init.erl"},{line,910}]}]}}
init terminating in do_boot ({undef,[{lorawan_app,start,[],[]},{init,start_em,1,[{_},{_}]},{init,do_boot,3,[{_},{_}]}]})

Crash dump is being written to: erl_crash.dump...done

Windows 7 OS. What did I do wrong?

**Comment by olegscorpion** [comment]
i install earl 19.2 , it all working.
